<?php
/**
 * Copyright 2015 Zerve, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace Omnipay\ElementExpress\Message;

use Omnipay\Common\Exception\InvalidResponseException;
use Omnipay\Common\Message\AbstractResponse;
use Omnipay\Common\Message\RequestInterface;

/**
 * ElementExpress Response
 */
class Response extends AbstractResponse
{
    /**
     * Constructor
     *
     * @param RequestInterface $request Request
     * @param string $data Data
     * @throws InvalidResponseException if $data is empty
     */
    public function __construct(RequestInterface $request, $data)
    {
        $this->request = $request;

        if (empty($data)) {
            throw new InvalidResponseException();
        }

        $implementation = new \DOMImplementation();
        $responseDom = $implementation->createDocument();
        $responseDom->preserveWhiteSpace = false;
        $responseDom->loadXML($data);
        $this->data = simplexml_import_dom(
            $responseDom->documentElement->firstChild
        );
    }

    public function isSuccessful()
    {
        if (isset($this->data->ExpressResponseCode)) {
            if ('0' === (string) $this->data->ExpressResponseCode) {
                return true;
            }
        }
        return false;
    }

    /**
     * Response code
     *
     * @return null|string A response code from the payment gateway
     */
    public function getCode()
    {
        return (string) $this->data->ExpressResponseCode;
    }

    /**
     * Response Message
     *
     * @return null|string A response message from the payment gateway
     */
    public function getMessage()
    {
        return (string) $this->data->ExpressResponseMessage;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        return (string) $this->data->Transaction->ReferenceNumber;
    }

    /**
     * Transaction Reference
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference()
    {
        return (string) $this->data->Transaction->TransactionID;
    }

    /**
     * Card Reference
     *
     * @return null|string A card reference for used in tokenized transactions.
     */
    public function getCardReference()
    {
        return (string) $this->data->PaymentAccount->PaymentAccountID;
    }

    /**
     * Approval Number
     *
     * @return null|string The approval number returned by the gateway
     */
    public function getApprovalNumber()
    {
        return (string) $this->data->Transaction->ApprovalNumber;
    }

    /**
     * Customer Token
     *
     * @return null|string The customer token used for token billing
     */
    public function getCustomerToken()
    {
        return (string) $this->data->PaymentAccount->PaymentAccountID;
    }

    /**
     * AVS Response
     *
     * @return null|string The AVS response for the card or token used.
     */
    public function getAvsResponse()
    {
        return (string) $this->data->Card->AVSResponseCode;
    }
}
